In [324]:
# down forget to upload abcd file to the source file in here, chose 'upload the session storage' *
# and download abcd file to your computer, it is right in the folder too *

import json
import pandas as pd
from pandas import json_normalize
import tensorflow as tf 

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

import os
import pandas as pd
!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer
embedder = SentenceTransformer('distilbert-base-nli-mean-tokens')

import re
!pip install preprocessor
import preprocessor as p

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from wordcloud import WordCloud

!pip install tweet-preprocessor
import preprocessor as p


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# New Section

In [325]:
df1= pd.read_csv('/content/customer_clusters.txt')

In [326]:
df1.isna().sum()

Unnamed: 0                                0
text_agent                                0
category_agent                            0
sub-category_agent                        0
speaker_customer                          0
text_customer                             0
clean _text_custumer                     33
cleaned_text_of_custumer_for_clusters    33
cluster_for_custumer                      0
clean_text_agent_corpus                   4
dtype: int64

In [327]:
df2= pd.read_csv('/content/csv_data (1).txt')

In [328]:
df2.isna().sum()

Unnamed: 0                            0
text_agent                            0
category_agent                        0
sub-category_agent                    0
speaker_customer                      0
text_customer                         0
clean _text_agent                     0
clean_text_agent_corpus               0
cleaned_text_of_agent_for_clusters    0
cluster_for_agent                     0
dtype: int64

In [329]:
df_m = pd.merge( df1, df2, left_index=True, right_index=True, how='inner', suffixes=('_agent', '_customer'))

In [330]:
df_m.isna().sum()

Unnamed: 0_agent                         0
text_agent_agent                         0
category_agent_agent                     0
sub-category_agent_agent                 0
speaker_customer_agent                   0
text_customer_agent                      0
clean _text_custumer                     1
cleaned_text_of_custumer_for_clusters    1
cluster_for_custumer                     0
clean_text_agent_corpus_agent            0
Unnamed: 0_customer                      0
text_agent_customer                      0
category_agent_customer                  0
sub-category_agent_customer              0
speaker_customer_customer                0
text_customer_customer                   0
clean _text_agent                        0
clean_text_agent_corpus_customer         0
cleaned_text_of_agent_for_clusters       0
cluster_for_agent                        0
dtype: int64

In [331]:
one_hot_encoded_data = pd.get_dummies(df_m, columns = ['cluster_for_custumer'])


In [332]:
y = df_m['cluster_for_agent'] 
X = df_m['cluster_for_custumer'] 

# X = df.drop('cluster_for_agent', axis=1) 
#ValueError: Found input variables with inconsistent numbers of samples: [9, 400]

In [333]:
y.shape

(500,)

In [334]:
X.shape

(500,)

In [335]:
X = X.values.reshape(-1,1)

In [336]:
X.shape

(500, 1)

In [337]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.20, random_state = 123)

In [338]:
from sklearn.metrics import roc_auc_score

# 1. Create the LogisticRegression model object 
# YOUR CODE HERE
model = LogisticRegression(max_iter=200)

# 2. Fit the model to the transformed training data
# YOUR CODE HERE
model.fit(X_train, y_train)

# 3. Use the predict_proba() method to make predictions on the test data 
# YOUR CODE HERE
pred_log = model.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [339]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred_log)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [340]:
from sklearn.metrics import precision_score, recall_score, f1_score
precision = precision_score(y_test, pred_log,average='micro') # How much Virigincia iris are correctly identified?
recall = recall_score(y_test, pred_log,average='micro') # How much Virginica predictions are correct?
f1 = f1_score(y_test, pred_log,average='micro')
print(precision, recall, f1)

0.01 0.01 0.01


In [341]:
acc_log = round(model.score(X_train, y_train) * 100, 2)
acc_log

3.5

In [342]:
print(pred_log)

[ 93  93  93  93  93  56  93  56  93  56  93  93  93  93  93  93  93  93
 243  93  93  93  93  93  56 243  93  93  93  56  93  56  93  93  56 243
  93  93  93  93  93  93  93  93 243  93 243  93 243 243 243 243 243  93
  56  93  93  93  93  93  93  56 243  93  93  56  93  93  56  56  56  93
  93  93 243  93  93  93  93  93 243  93  93  93  93  93  93  93  93  93
  93  93  93  93  93  93  93  56  93  93]


In [343]:
pred_log.shape

(100,)

In [344]:
print(X_test)

[[135]
 [234]
 [144]
 [ 85]
 [ 97]
 [  2]
 [124]
 [  3]
 [ 79]
 [ 16]
 [218]
 [ 85]
 [ 50]
 [183]
 [106]
 [ 86]
 [124]
 [ 56]
 [370]
 [183]
 [ 31]
 [245]
 [ 31]
 [227]
 [  2]
 [408]
 [283]
 [167]
 [233]
 [  7]
 [ 23]
 [  2]
 [ 28]
 [ 92]
 [  3]
 [417]
 [110]
 [ 51]
 [ 35]
 [ 75]
 [ 84]
 [163]
 [ 35]
 [ 28]
 [330]
 [ 84]
 [305]
 [ 23]
 [383]
 [361]
 [338]
 [426]
 [412]
 [ 92]
 [ 17]
 [261]
 [ 30]
 [164]
 [176]
 [209]
 [244]
 [  2]
 [360]
 [ 77]
 [ 42]
 [  6]
 [185]
 [124]
 [ 18]
 [  9]
 [  9]
 [123]
 [248]
 [243]
 [313]
 [248]
 [227]
 [ 98]
 [290]
 [134]
 [432]
 [ 51]
 [167]
 [207]
 [230]
 [227]
 [ 49]
 [240]
 [167]
 [ 52]
 [ 33]
 [262]
 [152]
 [173]
 [168]
 [162]
 [248]
 [  3]
 [124]
 [ 23]]


In [345]:
X_test.flatten()


array([135, 234, 144,  85,  97,   2, 124,   3,  79,  16, 218,  85,  50,
       183, 106,  86, 124,  56, 370, 183,  31, 245,  31, 227,   2, 408,
       283, 167, 233,   7,  23,   2,  28,  92,   3, 417, 110,  51,  35,
        75,  84, 163,  35,  28, 330,  84, 305,  23, 383, 361, 338, 426,
       412,  92,  17, 261,  30, 164, 176, 209, 244,   2, 360,  77,  42,
         6, 185, 124,  18,   9,   9, 123, 248, 243, 313, 248, 227,  98,
       290, 134, 432,  51, 167, 207, 230, 227,  49, 240, 167,  52,  33,
       262, 152, 173, 168, 162, 248,   3, 124,  23])

In [346]:
Cols = [[X_test,pred_log]]
 
# Create the pandas DataFrame with column name is provided explicitly
df = pd.DataFrame(Cols, columns=['X_text','pred'])

In [347]:
data = {'Prediction': [93,  93,  93,  93,  93,  56,  93,  56,  93,  56,  93,  93,  93,  93,  93,  93,  93,  93,
 243,  93,  93,  93,  93,  93,  56, 243,  93,  93,  93,  56,  93,  56,  93,  93,  56, 243,
  93,  93,  93,  93,  93,  93,  93,  93, 243,  93, 243,  93, 243, 243, 243, 243, 243,  93,
  56,  93,  93,  93,  93,  93,  93,  56, 243,  93,  93,  56,  93,  93,  56,  56,  56,  93,
  93,  93, 243,  93,  93,  93,  93,  93, 243,  93,  93,  93,  93,  93,  93,  93,  93,  93,
  93,  93,  93,  93,  93,  93,  93,  56,  93,  93],
        'The real Agent said': [135, 234, 144,  85,  97,   2, 124,   3,  79,  16, 218,  85,  50,
       183, 106,  86, 124,  56, 370, 183,  31, 245,  31, 227,   2, 408,
       283, 167, 233,   7,  23,   2,  28,  92,   3, 417, 110,  51,  35,
        75,  84, 163,  35,  28, 330,  84, 305,  23, 383, 361, 338, 426,
       412,  92,  17, 261,  30, 164, 176, 209, 244,   2, 360,  77,  42,
         6, 185, 124,  18,   9,   9, 123, 248, 243, 313, 248, 227,  98,
       290, 134, 432,  51, 167, 207, 230, 227,  49, 240, 167,  52,  33,
       262, 152, 173, 168, 162, 248,   3, 124,  23]}

In [348]:
df_comparison = pd.DataFrame(data)

In [349]:
df_comparison 

Prediction  The real Agent said
0           93                  135
1           93                  234
2           93                  144
3           93                   85
4           93                   97
..         ...                  ...
95          93                  162
96          93                  248
97          56                    3
98          93                  124
99          93                   23

[100 rows x 2 columns]

In [350]:
df= pd.read_csv('/content/agent_clusters (2)')


In [351]:
df.head(3)

Unnamed: 0                          text_agent  category_agent  \
0           0                                 hi!  product_defect   
1           1                 how can i help you?  product_defect   
2           2  sure, may i have your name please?  product_defect   

  sub-category_agent speaker_customer  \
0        return_size         customer   
1        return_size         customer   
2        return_size         customer   

                                       text_customer  \
0  hi! i need to return an item, can you help me ...   
1                                       crystal minh   
2                              i got the wrong size.   

                  clean _text_agent cleaned_text_of_agent_for_clusters  \
0                                hi                                 hi   
1                how can i help you                 how can i help you   
2  sure may i have your name please   sure may i have your name please   

   cluster_for_agent           clean_text_agent_corpus  
0                317                                hi  
1                 12                how can i help you  
2                142  sure may i have your name please

In [352]:
df_merged = pd.DataFrame(df[['cleaned_text_of_agent_for_clusters','text_customer']], index=df['cluster_for_agent'])

In [353]:
df_merged.head(3)

cleaned_text_of_agent_for_clusters  \
cluster_for_agent                                                      
317                                   hello how can i help you today   
12                                 good afternoon how can i help you   
142                according to the system you only are going to ...   

                               text_customer  
cluster_for_agent                             
317                no, that's it. thank you!  
12                     that's it. take care.  
142                              sanya afzal

In [354]:
print('The custumers text was:    ', df_merged['text_customer'][135].head(1))
print(' ')
print('The first option for an agnet to choose:          ', df_merged['cleaned_text_of_agent_for_clusters'][92].head(1))
print(' ')
print('The second option for an agnet to choose:         ', df_merged['cleaned_text_of_agent_for_clusters'][93].head(1))
print(' ')
print('The third option for an agnet to choose:          ', df_merged['cleaned_text_of_agent_for_clusters'][94].head(1))
print(' ')
print('The original cluster:')
print(df_comparison['The real Agent said'][0])
print(df_merged['cleaned_text_of_agent_for_clusters'][135].head(1))







The custumers text was:     cluster_for_agent
135    i have tried that and it does not seem to be h...
Name: text_customer, dtype: object
 
The first option for an agnet to choose:           cluster_for_agent
92    and to get your order details may i ask your u...
Name: cleaned_text_of_agent_for_clusters, dtype: object
 
The second option for an agnet to choose:          cluster_for_agent
93    i can see your order details it looks like the...
Name: cleaned_text_of_agent_for_clusters, dtype: object
 
The third option for an agnet to choose:           cluster_for_agent
94    oh im sorry to hear that but i should be able ...
Name: cleaned_text_of_agent_for_clusters, dtype: object
 
The original cluster:
135
cluster_for_agent
135    ok i will write a report about the slow speeds...
Name: cleaned_text_of_agent_for_clusters, dtype: object


In [355]:
sentences = [ 'ok i will write a report about the slow speeds','and to get your order details may i ask your id',' i can see your order details it looks like the return was started',
             'oh im sorry to hear that but i should be able to help you with that'] 

In [356]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('bert-base-nli-mean-tokens')

In [357]:

sentence_embeddings = model.encode(sentences)

In [358]:
sentence_embeddings.shape

(4, 768)

In [359]:
from sklearn.metrics.pairwise import cosine_similarity

In [360]:
cosine_similarity(
    [sentence_embeddings[0]],
    sentence_embeddings[1:]
)

array([[0.4100319 , 0.36744207, 0.5529167 ]], dtype=float32)

In [363]:
print('The best option for an agent to pick is a sentence from the cluster 94: oh im sorry to hear that but i should be able to help you with that')

The best option for an agent to pick is a sentence from the cluster 94: oh im sorry to hear that but i should be able to help you with that
